apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ideahub
  namespace: ideahub
spec:
  rules:
    - host: ideahub.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ideahub-web
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ideahub-api
                port:
                  number: 3333
